name: pokemon_compare
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.3
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
